// Amanda e Gabriel

#define TAC_SYMBOL 		1
#define TAC_ADD    		2
#define TAC_SUB    		3
#define TAC_MUL    		4
#define TAC_DIV    		5
#define TAC_G 	   		6
#define TAC_L 	   		7
#define TAC_LE	   		8
#define TAC_GE     		9
#define TAC_EQ 	   		10
#define TAC_NE	   		11
#define TAC_AND	   		12
#define TAC_OR	   		13
#define TAC_NOT	   		14
#define TAC_ASSIGN		17
#define TAC_VEC_WRITE	18
#define TAC_VEC_READ	19
#define TAC_RETURN		20
#define TAC_PRINT		21
#define TAC_READ		22
#define TAC_CALL		26
#define TAC_ARG			27
#define TAC_IFZ			28
#define TAC_LABEL		29
#define TAC_JUMP		30
#define TAC_IFLESS		31
#define TAC_INC			32
#define TAC_MOVE		33
#define TAC_BEGIN_FUNC 	34
#define TAC_END_FUNC 	35
